
# Build settings
[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # Set the correct MIME types for JavaScript files
    Content-Type = '''
      application/javascript; charset=utf-8
    '''

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Handle module scripts properly
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Add correct types for other assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"

# Add correct types for font files
[[headers]]
  for = "/*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

# Create a special rule for build/assets
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
