# Build settings
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# Add this redirect rule for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# JavaScript files
[[headers]]
  for = "/*.{js,mjs}"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.{woff,woff2}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
